In [3]:
import mysql.connector
conn = mysql.connector.connect(user='root', password='root', database='mathmodel')
cursor = conn.cursor()
#while(true):
    #cursor.execute('insert into user (id, name) values (%s, %s)', ['1', 'Michael'])
cursor.execute('select count(name) from table1 where jingdu-22.56614225 <=0.01 and weidu-113.9808368 <=0.01')
values = cursor.fetchall()
print(values)
cursor.close()
conn.close()

[(37,)]

In [5]:
import mysql.connector
conn = mysql.connector.connect(user='root', password='root', database='mathmodel')
cursor = conn.cursor()
#i=1
#while(i <= 835):
    #cursor.execute('insert into user (id, name) values (%s, %s)', ['1', 'Michael'])
cursor.execute('select jingdu from table1 where id = 1')
jingdu = cursor.fetchall()
cursor.execute('select weidu from table1 where id = 1')
weidu = cursor.fetchall()
    #cursor.execute('select count(name) from table1 where jingdu-22.56614225 <=0.01 and weidu-113.9808368 <=0.01')
    #values = cursor.fetchall()
print(jingdu,weidu)
    #i = i + 1
cursor.close()
conn.close()

[(Decimal('22.56614225'),)] [(Decimal('113.9808368'),)]

In [6]:
import mysql.connector
conn = mysql.connector.connect(user='root', password='root', database='mathmodel')
cursor = conn.cursor()
#i=1
#while(i <= 835):
    #cursor.execute('insert into user (id, name) values (%s, %s)', ['1', 'Michael'])
cursor.execute('select jingdu from table1 where id = 1')
jingdu = cursor.fetchall()
cursor.execute('select weidu from table1 where id = 1')
weidu = cursor.fetchall()
cursor.execute('select count(name) from table1 where jingdu- %s<=0.01 and weidu-%s <=0.01',[jingdu,weidu])
value = cursor.fetchall()
print(value)
    #i = i + 1
cursor.close()
conn.close()

ProgrammingError: Failed processing format-parameters; Python 'list' cannot be converted to a MySQL type

In [12]:
import mysql.connector
conn = mysql.connector.connect(user='root', password='root', database='mathmodel')
cursor = conn.cursor()
#while(true):
    #cursor.execute('insert into user (id, name) values (%s, %s)', ['1', 'Michael'])
cursor.execute('select count(name) from table1 where jingdu-22.56614225 <=0.01 and weidu-113.9808368 <=0.01')
values = cursor.fetchall()
print(values[0][0])
print(type(values[0][0]))
cursor.close()
conn.close()

37
<class 'int'>

In [13]:
import mysql.connector
conn = mysql.connector.connect(user='root', password='root', database='mathmodel')
cursor = conn.cursor()
#i=1
#while(i <= 835):
    #cursor.execute('insert into user (id, name) values (%s, %s)', ['1', 'Michael'])
cursor.execute('select jingdu from table1 where id = 1')
jingdu = cursor.fetchall()
cursor.execute('select weidu from table1 where id = 1')
weidu = cursor.fetchall()
    #cursor.execute('select count(name) from table1 where jingdu-22.56614225 <=0.01 and weidu-113.9808368 <=0.01')
    #values = cursor.fetchall()
print(jingdu[0][0],weidu[0][0])
    #i = i + 1
cursor.close()
conn.close()

22.56614225 113.9808368

In [17]:
import mysql.connector
conn = mysql.connector.connect(user='root', password='root', database='mathmodel')
cursor = conn.cursor()
#i=1
#while(i <= 835):
    #cursor.execute('insert into user (id, name) values (%s, %s)', ['1', 'Michael'])
cursor.execute('select jingdu from table1 where id = 1')
jingdu = cursor.fetchall()
j1 = jingdu[0][0]
cursor.execute('select weidu from table1 where id = 1')
weidu= cursor.fetchall()
w1 = weidu[0][0]
cursor.execute('select count(name) from table1 where jingdu- %s<=0.01 and weidu-%s <=0.01',[j1,w1])
value = cursor.fetchall()
v1 = value[0][0]
print(v1)
    #i = i + 1
cursor.close()
conn.close()

37

In [29]:
import mysql.connector
conn = mysql.connector.connect(user='root', password='root', database='mathmodel')
cursor = conn.cursor()
i=1
while(i <= 835):
    #cursor.execute('insert into user (id, name) values (%s, %s)', ['1', 'Michael'])
    cursor.execute('select jingdu from table1 where id = %s',[i])
    jingdu = cursor.fetchall()
    j1 = jingdu[0][0]
    cursor.execute('select weidu from table1 where id = %s',[i])
    weidu= cursor.fetchall()
    w1 = weidu[0][0]
    cursor.execute('select count(name) from table1 where jingdu- %s<=0.01 and weidu-%s <=0.01',[j1,w1])
    value = cursor.fetchall()
    v1 = value[0][0]
    print(v1)
    i = i + 1
cursor.close()
conn.close()

37
51
35
55
29
54
26
29
2
11
14
17
25
8
7
11
8
2
25
7
5
16
16
29
27
6
6
21
37
64
39
17
25
64
41
17
104
94
104
69
81
88
155
80
59
56
132
77
88
122
64
82
169
109
90
184
13
112
59
66
79
75
94
187
145
113
63
79
100
15
142
20
98
26
68
39
159
15
87
60
97
74
67
64
5
30
21
64
8
70
67
101
7
10
4
104
7
3
21
55
113
35
104
5
6
63
35
14
7
51
3
6
70
2
3
105
113
4
15
6
159
6
12
9
37
362
277
237
306
218
268
252
360
248
246
324
219
297
242
283
242
245
243
251
216
236
244
234
234
335
242
229
193
267
242
231
305
110
152
63
350
224
244
94
199
314
147
354
401
288
100
199
221
240
178
165
2
8
124
164
180
266
246
185
185
189
220
230
46
212
253
217
275
301
239
271
246
20
10
8
122
165
122
20
20
18
9
4
9
242
138
148
257
138
138
143
142
151
282
174
154
3
137
177
99
204
230
172
179
134
157
167
219
165
169
167
117
172
169
177
172
137
139
152
165
186
146
157
186
148
166
162
161
138
162
166
163
144
115
158
110
167
55
160
87
15
92
63
95
94
45
107
12
81
57
67
71
63
63
86
89
57
48
55
66
68
86
63
53
111
55
489
68
77
474
434
460
546
489
484
484
488
697
487
217
489
488
283
233
274
486
266
200
183
234
192
235
283
193
235
314
237
267
160
169
247
258
192
171
209
261
168
236
163
314
145
231
172
170
173
314
217
244
148
209
174
232
275
243
169
258
144
180
163
66
6
12
43
53
36
7
38
114
52
171
268
345
244
30
138
345
264
254
320
68
106
63
164
164
94
177
189
267
14
1
212
194
20
185
20
187
152
184
128
143
146
338
218
341
201
415
104
62
111
45
24
148
96
104
24
46
97
63
64
94
84
74
481
63
45
85
137
72
489
347
443
256
182
488
266
489
201
236
223
152
163
158
145
141
18
47
144
55
38
78
51
38
34
23
67
61
21
57
38
8
63
138
6
21
119
258
17
148
21
37
60
7
31
213
320
167
185
156
254
201
228
261
199
59
135
204
39
246
52
39
16
133
205
32
51
319
73
230
285
168
215
212
255
236
51
43
242
245
169
310
45
47
101
57
180
37
140
19
13
170
19
294
167
300
287
255
154
176
61
31
251
225
290
204
194
180
305
152
157
230
147
104
17
293
15
55
7
16
38
10
16
2
6
79
129
16
16
140
113
79
117
13
110
72
83
8
2
13
7
22
22
79
92
6
81
5
74
80
9
34
54
72
4
278
54
14
70
72
11
23
50
1
67
35
5
41
41
41
8
29
12
53
47
22
28
27
50
49
19
54
48
22
39
58
22
53
82
236
33
268
45
43
106
415
189
176
35
250
54
139
130
151
61
294
61
80
50
256
137
153
151
112
238
35
178
142
336
120
351
278
248
343
246
240
316
257
240
250
4
11
9
18
25
43
6
6
2
31
5
2
23
5
21
20
26
6
4
7
18
79
19
25
113
7
75
16
20
7
13
37
71
393
119
29
74
25
76
48
84
240
257
210
235
61
80
108
240
130
198
357
150
377
66
36
321
153
26
263
36
280
140
50
125
45
388
141
62
158
357
336
204
212
280
19
4
30
17
46
3
126
7
38
163
100
104
36
216
104
196
23
213
36
254
219
343
425
56
133
272
29
350
201
25
221
169
361
238
207
256
232
181
161
217
268
246
205
200
435
422
79
285
8
11
201
171
130
146
13
108
249
20
301
135
99
76
36
59
109
73
13
78
10
10
78
89
33
168
408
126
235
392
236
233
78
6
22
22
22
8
81
22
23
33
22
31
4
42
23
33
11
15
90
193
6
103
59
15
68
272
74

In [27]:
import mysql.connector
conn = mysql.connector.connect(user='root', password='root', database='mathmodel')
cursor = conn.cursor()
i=1
#while(i <= 835):
    #cursor.execute('insert into user (id, name) values (%s, %s)', ['1', 'Michael'])
cursor.execute('select jingdu from table1 where id = %s',[i])
jingdu = cursor.fetchall()
#cursor.execute('select weidu from table1 where id = 1')
#weidu = cursor.fetchall()
    #cursor.execute('select count(name) from table1 where jingdu-22.56614225 <=0.01 and weidu-113.9808368 <=0.01')
    #values = cursor.fetchall()
print(jingdu)
    #i = i + 1
cursor.close()
conn.close()

[(Decimal('22.56614225'),)]

In [30]:
import mysql.connector
conn = mysql.connector.connect(user='root', password='root', database='mathmodel')
cursor = conn.cursor()
i=1
while(i <= 835):
    #cursor.execute('insert into user (id, name) values (%s, %s)', ['1', 'Michael'])
    cursor.execute('select jingdu from table1 where id = %s',[i])
    jingdu = cursor.fetchall()
    j1 = jingdu[0][0]
    cursor.execute('select weidu from table1 where id = %s',[i])
    weidu= cursor.fetchall()
    w1 = weidu[0][0]
    for j in range(1877):
        cursor.execute('select jingdu from table2 where id = %s',[j])
        jingdu2 = cursor.fetchall()
        j2 = jingdu2[0][0]
        cursor.execute('select weidu from table2 where id = %s',[j])
        weidu2= cursor.fetchall()
        w2 = weidu2[0][0]
        cursor.execute('select count(name) from table1 where %s - %s<=0.01 and %s - %s <=0.01',[j1,j2,w1,w2])
        value = cursor.fetchall()
        v2 = value[0][0]
        print(v2)
        j = j + 1
    i = i + 1
cursor.close()
conn.close()

ProgrammingError: 1054 (42S22): Unknown column 'id' in 'where clause'

In [11]:
#问题2
import mysql.connector
conn = mysql.connector.connect(user='root', password='root', database='mathmodel')
cursor = conn.cursor()
i=1
while(i <= 835):
    #cursor.execute('insert into user (id, name) values (%s, %s)', ['1', 'Michael'])
    cursor.execute('select jingdu from table1 where id = %s',[i])
    jingdu = cursor.fetchall()
    j1 = jingdu[0][0]
    cursor.execute('select weidu from table1 where id = %s',[i])
    weidu= cursor.fetchall()
    w1 = weidu[0][0]
    cursor.execute('select count(id) from table2 where (jingdu- %s<=0.01 and jingdu- %s>=-0.01) and (weidu-%s <=0.01 and weidu-%s >= -0.01)',[j1,j1,w1,w1])
    value = cursor.fetchall()
    v2 = value[0][0]
    print(v2)
    i = i + 1
cursor.close()
conn.close()

0
15
5
1
3
1
7
4
1
9
7
10
7
4
4
10
9
1
7
4
0
9
9
4
2
3
4
2
0
0
9
4
5
1
13
7
1
1
2
17
3
3
5
9
8
5
4
4
8
1
4
3
1
4
2
0
2
0
3
7
3
9
1
1
2
2
14
2
3
6
2
6
4
10
13
4
4
6
0
3
4
7
9
11
6
4
6
2
6
1
11
1
4
4
1
2
4
3
6
6
3
3
1
1
4
7
2
4
10
0
0
5
7
3
4
5
4
1
3
2
4
3
2
10
1
1
9
4
0
3
7
16
0
13
6
1
8
4
1
1
3
15
1
17
10
7
2
7
7
0
3
3
0
2
3
3
1
2
18
1
0
3
6
0
5
0
0
0
0
4
1
5
4
3
6
1
3
1
3
21
15
8
6
6
8
7
3
2
0
7
16
11
10
0
3
4
6
0
0
0
2
6
2
0
0
0
1
0
1
3
4
1
1
2
3
0
4
5
2
7
1
0
2
6
0
1
0
6
2
5
2
0
1
4
2
5
5
1
12
6
9
0
13
10
0
2
3
5
2
4
0
1
8
10
8
6
9
2
1
8
2
13
4
9
11
0
1
1
0
0
0
1
0
0
3
3
2
1
3
1
1
3
2
4
4
3
1
4
4
1
4
2
3
0
1
1
0
0
2
2
3
2
0
2
2
3
2
1
4
6
2
5
2
6
4
9
4
5
1
6
0
4
5
5
3
5
6
0
3
5
6
4
6
6
0
5
1
5
3
2
0
2
7
4
5
2
3
7
5
2
6
5
2
4
7
3
2
2
8
7
4
0
1
16
2
4
3
2
4
4
3
10
0
1
6
10
3
20
18
0
5
10
8
0
0
6
4
0
8
0
6
16
0
4
4
8
2
1
2
3
0
9
2
1
0
0
1
10
0
0
0
10
4
1
0
2
3
1
3
2
7
3
5
3
2
0
0
1
3
3
3
7
6
2
1
3
1
2
4
0
4
0
3
0
4
16
6
4
3
1
8
7
4
1
2
13
2
3
0
0
7
4
9
5
6
2
6
11
9
0
10
6
4
10
6
7
10
7
3
8
9
3
13
7
3
3
1
0
3
7
1
0
2
1
0
1
2
0
1
3
1
3
2
2
1
1
1
1
5
1
6
0
2
1
0
2
0
0
1
1
9
1
1
3
1
3
1
1
1
3
0
0
3
2
4
1
3
2
1
1
0
0
0
1
1
1
1
1
1
1
0
0
2
2
1
3
1
2
1
1
0
0
0
0
0
0
1
1
2
1
0
2
1
1
1
1
6
1
5
1
1
3
7
1
0
1
0
7
0
1
4
1
1
0
2
0
4
3
1
2
3
6
3
0
4
2
2
2
4
1
8
1
1
1
3
2
5
4
1
2
1
3
4
0
1
0
1
3
0
3
2
1
1
0
0
2
0
3
4
1
1
1
1
1
0
1
1
1
2
0
0
1
0
0
1
1
0
3
0
0
0
1
4
0
1
1
1
3
0
0
1
0
1
0
1
1
1
1
0
1
4
2
1
1
3
1
2
0
4
1
1
2
3
1
1
1
1
3
4
3
3
2
0
4
0
1
1
1
6
1
0
5
0
4
1
1
1
2
1
0
2
1
5
0
1
3
0
2
0
1
0
2
3
1
1
0
1
1
2
3
4
2
3
1
0
0
4
0
1
1
1
2
4
6
5
1
1
1
1
2
0
3
0
1
1
2
0
0
2
3
1
2
1
0
1
3
0
1
1
0
1
1
0
1
4
0
0
0
1
1
1
4
4
1
0
1
0
1
1
3
1
0
1
2
0
3
5
1
1
1
4
4
5
1
2
3
1
1
4
3
0
2
4
2
1
3
1
3
1
1
9
2
1
6
1

In [3]:
#问题1
import mysql.connector
conn = mysql.connector.connect(user='root', password='root', database='mathmodel')
cursor = conn.cursor()
i=1
while(i <= 835):
    #cursor.execute('insert into user (id, name) values (%s, %s)', ['1', 'Michael'])
    cursor.execute('select jingdu from table1 where id = %s',[i])
    jingdu = cursor.fetchall()
    j1 = jingdu[0][0]
    cursor.execute('select weidu from table1 where id = %s',[i])
    weidu= cursor.fetchall()
    w1 = weidu[0][0]
    cursor.execute('select count(name) from table1 where (jingdu- %s<=0.05 and jingdu- %s>=-0.05) and (weidu-%s <=0.05 and weidu-%s >= -0.05)',[j1,j1,w1,w1])
    value = cursor.fetchall()
    v1 = value[0][0]
    print(v1)
    i = i + 1
cursor.close()
conn.close()

23
8
19
2
33
2
29
32
21
37
33
34
27
25
24
38
30
21
27
21
20
32
34
17
19
19
29
38
25
17
12
36
33
18
12
34
15
2
14
12
18
6
9
11
18
6
11
15
9
2
18
19
1
11
6
6
18
7
10
18
19
13
2
6
8
11
17
16
9
13
6
9
9
11
14
6
10
13
5
19
15
14
9
14
16
12
14
3
16
9
18
11
12
17
15
11
12
11
14
15
11
6
13
24
12
17
9
16
30
6
11
28
19
11
13
15
11
15
21
27
10
17
20
36
14
2
29
38
18
44
18
27
2
21
41
7
38
17
6
6
10
22
40
27
46
18
40
16
16
4
10
10
9
5
10
10
10
27
36
26
4
11
44
18
46
15
17
2
2
31
22
46
39
39
48
27
14
7
27
39
48
19
41
51
46
48
45
44
6
45
25
43
20
19
38
31
40
6
11
11
18
20
18
10
10
10
7
1
7
10
35
20
8
14
36
14
14
36
5
20
16
4
13
19
1
8
20
20
22
31
18
30
19
20
22
20
29
23
42
19
42
15
35
38
29
36
30
50
36
48
22
21
35
36
40
32
36
31
10
25
27
42
28
49
15
2
25
26
29
18
6
17
2
15
33
32
30
26
22
21
33
20
29
29
28
31
34
28
28
17
29
14
31
32
14
1
1
1
14
14
14
14
1
14
47
14
14
6
51
8
14
34
56
54
48
47
50
32
47
49
15
45
34
46
48
45
26
45
42
50
38
49
50
48
15
34
52
49
37
44
15
47
47
36
50
43
44
21
46
48
38
34
40
41
18
29
8
18
15
19
12
23
12
8
43
23
9
39
14
35
9
20
7
6
18
17
21
40
41
18
53
47
34
11
1
45
47
10
46
7
51
36
15
25
14
33
5
19
5
20
2
17
20
10
6
2
15
17
1
2
14
16
28
21
18
32
31
14
32
13
14
28
31
14
9
1
39
12
14
36
14
49
50
51
17
18
16
14
14
19
12
9
8
23
12
8
12
8
12
1
19
14
6
16
12
17
14
17
9
9
23
36
50
8
11
15
26
10
45
3
48
51
40
19
47
38
21
54
33
36
50
39
29
44
39
13
10
12
19
44
17
12
11
30
9
9
20
15
12
14
15
11
11
16
30
9
8
7
14
10
17
2
20
18
12
20
25
17
27
31
28
11
3
16
15
19
23
30
9
31
19
29
20
17
32
13
10
19
31
10
7
10
9
2
9
10
1
5
11
6
9
15
29
18
13
20
9
19
10
32
6
1
7
4
20
11
11
36
5
36
5
29
34
11
22
34
35
5
7
34
8
34
37
11
14
25
1
39
43
5
39
41
42
7
33
13
46
48
28
33
30
44
35
28
34
47
29
41
42
29
41
11
12
40
6
28
38
10
2
8
7
19
10
18
8
9
12
16
21
17
12
15
26
2
12
12
13
26
10
4
9
3
11
3
22
25
16
23
12
30
24
12
23
5
11
7
16
9
3
5
5
3
35
16
3
16
6
15
9
9
4
5
15
16
11
18
6
20
16
13
19
19
15
19
16
6
14
2
14
4
6
13
48
8
15
9
16
32
36
12
10
12
9
3
14
11
13
11
10
7
2
17
7
11
7
11
15
12
13
1
11
11
10
14
3
13
6
8
16
6
15
19
4
3
6
9
2
16
19
19
11
9
10
8
4
30
11
7
12
6
7
17
12
26
15
18
3
6
23
10
17
23
10
30
11
21
6
18
16
27
4
25
2
2
13
5
6
5
8
20
3
14
4
15
21
12
15
12
19
4
22
36
24
4
5
18
15
5
13
23
19
6
9
4
2
12
29
12
18
4
22
22
18
5
20
23
22
19
23
36
1
40
23
30
9
11
37
29
10
19
41
15
14
26
11

In [14]:
#问题3
import mysql.connector
conn = mysql.connector.connect(user='root', password='root', database='mathmodel')
cursor = conn.cursor()
i=1
while(i <= 835):
    #cursor.execute('insert into user (id, name) values (%s, %s)', ['1', 'Michael'])
    cursor.execute('select jingdu from table1 where id = %s',[i])
    jingdu = cursor.fetchall()
    j1 = jingdu[0][0]
    cursor.execute('select weidu from table1 where id = %s',[i])
    weidu= cursor.fetchall()
    w1 = weidu[0][0]
    cursor.execute('select SUM(score) from table2 where (jingdu- %s<=0.01 and jingdu- %s>=-0.01) and (weidu-%s <=0.01 and weidu-%s >= -0.01)',[j1,j1,w1,w1])
    value = cursor.fetchall()
    v2 = value[0][0]
    print(v2)
    i = i + 1
cursor.close()
conn.close()

None
391.52250000000000000000
38072.10340000000000000000
0.36360000000000000000
10977.88210000000000000000
0.36360000000000000000
140.41640000000000000000
337.99300000000000000000
19.92310000000000000000
822.11740000000000000000
410.37980000000000000000
577.51050000000000000000
161.74520000000000000000
60.10910000000000000000
174.01050000000000000000
822.15840000000000000000
448.56390000000000000000
19.92310000000000000000
161.74520000000000000000
174.01050000000000000000
None
418.88970000000000000000
440.46530000000000000000
63.75390000000000000000
976.37210000000000000000
22.28610000000000000000
58.14820000000000000000
20.30100000000000000000
None
None
1389.11120000000000000000
208.67050000000000000000
11313.71080000000000000000
19.92310000000000000000
1943.82990000000000000000
537.32450000000000000000
19.92310000000000000000
0.36930000000000000000
21.91540000000000000000
1043.54430000000000000000
121.13980000000000000000
213.35880000000000000000
240.80850000000000000000
575.01700000000000000000
901.93440000000000000000
848.12340000000000000000
538.61820000000000000000
157.82860000000000000000
162.83800000000000000000
19.92310000000000000000
258.45560000000000000000
121.13980000000000000000
2.00000000000000000000
24.27130000000000000000
232.55580000000000000000
None
79.69250000000000000000
None
446.76510000000000000000
1609.82030000000000000000
121.13980000000000000000
488.62940000000000000000
0.36930000000000000000
39.84630000000000000000
108.67060000000000000000
65.60860000000000000000
1641.65430000000000000000
20.01610000000000000000
338.70830000000000000000
422.34260000000000000000
39.84620000000000000000
486.12550000000000000000
182.42950000000000000000
246.15970000000000000000
2082.60210000000000000000
23.99900000000000000000
481.32680000000000000000
422.34260000000000000000
None
79.73350000000000000000
81.68480000000000000000
484.48780000000000000000
237.05140000000000000000
1277.30250000000000000000
1582.58790000000000000000
604.33660000000000000000
285.61500000000000000000
39.84620000000000000000
82.71360000000000000000
21.00000000000000000000
1632.57540000000000000000
1.99230000000000000000
99.61560000000000000000
1559.33910000000000000000
0.36360000000000000000
21.91540000000000000000
99.61560000000000000000
124.26020000000000000000
285.61500000000000000000
801.07240000000000000000
22.27900000000000000000
22.00670000000000000000
19.92310000000000000000
0.09130000000000000000
144.18330000000000000000
724.78240000000000000000
242.71510000000000000000
401.45110000000000000000
1210.05590000000000000000
None
None
844.16710000000000000000
242.72990000000000000000
83.68480000000000000000
95.68450000000000000000
251.12730000000000000000
24.27130000000000000000
0.36360000000000000000
99.61560000000000000000
64.38330000000000000000
1911.83730000000000000000
2.45600000000000000000
79.69250000000000000000
861.96370000000000000000
19.92310000000000000000
19.92310000000000000000
163.36950000000000000000
103.97230000000000000000
None
81.68480000000000000000
2884.22630000000000000000
2771.13840000000000000000
None
5152.36290000000000000000
17435.42890000000000000000
2.00000000000000000000
367.69810000000000000000
159.38500000000000000000
31.50770000000000000000
19.92310000000000000000
15018.03220000000000000000
5360.32750000000000000000
19.92310000000000000000
2890.67720000000000000000
182.99660000000000000000
131.83340000000000000000
0.73570000000000000000
195.40600000000000000000
195.40600000000000000000
None
15018.03220000000000000000
15018.03220000000000000000
None
4.83320000000000000000
15018.03220000000000000000
15018.03220000000000000000
19.92310000000000000000
181.30050000000000000000
388.94910000000000000000
1.99230000000000000000
None
20.65880000000000000000
5348.02530000000000000000
None
101.60790000000000000000
None
None
None
None
26199.71780000000000000000
59.76940000000000000000
101.60790000000000000000
61.76160000000000000000
5.98460000000000000000
3813.09640000000000000000
19.92310000000000000000
79.69250000000000000000
1.99230000000000000000
40.20020000000000000000
2043.90150000000000000000
1163.48640000000000000000
104.36080000000000000000
17435.42890000000000000000
1135.66990000000000000000
336.70090000000000000000
878.22910000000000000000
81.68480000000000000000
81.25450000000000000000
None
297.00950000000000000000
2316.71990000000000000000
262.68910000000000000000
39725.98150000000000000000
None
195.05560000000000000000
10428.90920000000000000000
17435.42890000000000000000
None
None
None
81.68480000000000000000
163.75040000000000000000
81.68480000000000000000
None
None
None
1.99230000000000000000
None
1.99230000000000000000
15018.03220000000000000000
43.83080000000000000000
39.84630000000000000000
7.52680000000000000000
23.90770000000000000000
41.83850000000000000000
None
67.73860000000000000000
664.18150000000000000000
1.02420000000000000000
66.12700000000000000000
39.84630000000000000000
None
23.90770000000000000000
46.20390000000000000000
None
19.92310000000000000000
None
64.13470000000000000000
21.91540000000000000000
189.96240000000000000000
43.83090000000000000000
None
92.98750000000000000000
42.21930000000000000000
21.91540000000000000000
62.14240000000000000000
157.20970000000000000000
19.92310000000000000000
231.46870000000000000000
46.20390000000000000000
167.71470000000000000000
None
486.72630000000000000000
365.45480000000000000000
None
40.21990000000000000000
22.27900000000000000000
873.20380000000000000000
40.21990000000000000000
254.43940000000000000000
None
19.92310000000000000000
92.91100000000000000000
1287.89510000000000000000
188.54980000000000000000
69.36690000000000000000
172.60350000000000000000
21.91540000000000000000
19.92310000000000000000
91.28230000000000000000
181.30050000000000000000
255.28990000000000000000
119.53870000000000000000
668.65950000000000000000
12961.70390000000000000000
None
1.99230000000000000000
1.99230000000000000000
None
None
None
19.92310000000000000000
None
None
732.34300000000000000000
81.68480000000000000000
0.46800000000000000000
1.99230000000000000000
80.82020000000000000000
1.99230000000000000000
19.92310000000000000000
95.17380000000000000000
3.98460000000000000000
119.53870000000000000000
40.31420000000000000000
39.93920000000000000000
19.92310000000000000000
40.31420000000000000000
119.53870000000000000000
23.43210000000000000000
119.53870000000000000000
32.93120000000000000000
81.68480000000000000000
None
19.92310000000000000000
219.97010000000000000000
None
None
32.93120000000000000000
32.93120000000000000000
52.85430000000000000000
32.93120000000000000000
None
32.93120000000000000000
156.01080000000000000000
52.85430000000000000000
32.93120000000000000000
0.36360000000000000000
5329.36590000000000000000
187.20860000000000000000
32.93120000000000000000
121.58420000000000000000
21.92310000000000000000
3802.00310000000000000000
175.96970000000000000000
312.65270000000000000000
5329.36590000000000000000
26279.41030000000000000000
1.99230000000000000000
5369.21210000000000000000
None
35.89740000000000000000
121.58420000000000000000
104.59640000000000000000
67.73860000000000000000
61.79740000000000000000
25.33730000000000000000
None
60.05440000000000000000
192.83120000000000000000
233.44320000000000000000
79.69240000000000000000
5369.21210000000000000000
124.51950000000000000000
None
115.17880000000000000000
1.99230000000000000000
3641.89770000000000000000
60.05440000000000000000
59.76940000000000000000
None
156.01080000000000000000
95.66670000000000000000
181.30040000000000000000
192.83120000000000000000
59.76940000000000000000
3895.84050000000000000000
1834.54350000000000000000
177.96200000000000000000
39.84620000000000000000
233.44320000000000000000
115.17880000000000000000
20.01610000000000000000
24.26890000000000000000
1609.82030000000000000000
58.10720000000000000000
13.41220000000000000000
111.06500000000000000000
811.79150000000000000000
38191.64220000000000000000
99.61560000000000000000
None
19.92310000000000000000
476.41570000000000000000
59.76940000000000000000
61.76160000000000000000
268.60950000000000000000
3.99230000000000000000
63.75390000000000000000
43.83080000000000000000
268.60950000000000000000
1853.27230000000000000000
None
0.98470000000000000000
321.13510000000000000000

13977.53760000000000000000
80.82020000000000000000
2023.97840000000000000000
2095.98710000000000000000
None
980.98530000000000000000
9548.12930000000000000000
38422.54470000000000000000
None
None
27.01100000000000000000
189.76560000000000000000
None
336.70090000000000000000
None
1135.66990000000000000000
1308.07880000000000000000
None
70.69680000000000000000
67.73860000000000000000
140.06620000000000000000
99.61560000000000000000
322.13260000000000000000
99.61560000000000000000
59.76930000000000000000
None
13975.53760000000000000000
23.90770000000000000000
19.92310000000000000000
None
None
1.99230000000000000000
13977.53760000000000000000
None
None
None
13977.53760000000000000000
59.86230000000000000000
19.92310000000000000000
None
21.91540000000000000000
81.68480000000000000000
19.92310000000000000000
81.68480000000000000000
77.35390000000000000000
543.81800000000000000000
1406.00810000000000000000
98.06400000000000000000
52.85430000000000000000
168.99380000000000000000
None
None
1.99230000000000000000
52.85430000000000000000
6127.12100000000000000000
52.85430000000000000000
214.74660000000000000000
5369.21210000000000000000
161.98770000000000000000
39.84630000000000000000
123.52340000000000000000
19.92310000000000000000
21.91540000000000000000
67.73860000000000000000
None
110.24230000000000000000
None
40.22850000000000000000
None
157.82860000000000000000
397.08540000000000000000
188.46240000000000000000
103.60800000000000000000
59.76930000000000000000
19.92310000000000000000
942.85790000000000000000
287.60730000000000000000
828.20030000000000000000
19.92310000000000000000
39.84620000000000000000
1639.66200000000000000000
23.90770000000000000000
2.45600000000000000000
None
None
43.24390000000000000000
208.67050000000000000000
3999.16390000000000000000
497.40190000000000000000
67.86160000000000000000
39.84620000000000000000
844.25870000000000000000
394.12210000000000000000
174.93800000000000000000
None
123.36320000000000000000
1135.66990000000000000000
121.53100000000000000000
5072.67040000000000000000
192.46580000000000000000
281.08720000000000000000
5070.82880000000000000000
179.39930000000000000000
113.76170000000000000000
188.79850000000000000000
274.60720000000000000000
145.93500000000000000000
283.84220000000000000000
1001.02360000000000000000
145.93500000000000000000
40.57630000000000000000
1.99230000000000000000
None
151.00980000000000000000
1001.02360000000000000000
1.99230000000000000000
None
79.69260000000000000000
2.00000000000000000000
None
9495.81260000000000000000
147.88120000000000000000
None
0.09160000000000000000
251.03140000000000000000
19.92310000000000000000
40.30920000000000000000
40.21760000000000000000
39.84620000000000000000
2.00000000000000000000
1.99230000000000000000
19.92310000000000000000
1.99230000000000000000
99.61550000000000000000
0.36360000000000000000
2338.74640000000000000000
None
20.28530000000000000000
19.92310000000000000000
None
20.28530000000000000000
None
None
20.25530000000000000000
2.00000000000000000000
20716.41600000000000000000
19.92310000000000000000
19.92310000000000000000
59.76930000000000000000
2.00000000000000000000
253.39660000000000000000
183.23650000000000000000
2.00000000000000000000
19.92310000000000000000
822.77610000000000000000
None
None
127.09330000000000000000
71.32590000000000000000
60.32420000000000000000
1.99230000000000000000
69936.81590000000000000000
4.00000000000000000000
2.00000000000000000000
271.47540000000000000000
None
None
None
1.99230000000000000000
271.47540000000000000000
41.83860000000000000000
0.36500000000000000000
3.98460000000000000000
19.92310000000000000000
1.99230000000000000000
None
None
3.99230000000000000000
21.91540000000000000000
0.83980000000000000000
37.07570000000000000000
271.47540000000000000000
27.39110000000000000000
1.99230000000000000000
19.92310000000000000000
None
None
None
None
None
None
19.92310000000000000000
55.54740000000000000000
5.98460000000000000000
19.92310000000000000000
None
256.22240000000000000000
19.92310000000000000000
41.83860000000000000000
83.67720000000000000000
19.92310000000000000000
351.44240000000000000000
2.00000000000000000000
147.36230000000000000000
19.92310000000000000000
19.92310000000000000000
23.91540000000000000000
371.36550000000000000000
123.52340000000000000000
None
59.76940000000000000000
None
1962.33140000000000000000
None
2.00000000000000000000
167.85040000000000000000
425.55390000000000000000
425.55390000000000000000
None
39.84620000000000000000
None
144.84500000000000000000
41.83850000000000000000
19.54320000000000000000
39.84620000000000000000
41.84620000000000000000
981.10050000000000000000
470.66680000000000000000
None
585.55270000000000000000
21.91540000000000000000
21.92310000000000000000
106.08870000000000000000
162.77580000000000000000
19.54320000000000000000
2411.27010000000000000000
19.92310000000000000000
0.09160000000000000000
168.35460000000000000000
321.61870000000000000000
199.35000000000000000000
215.66590000000000000000
70136.04720000000000000000
19.92310000000000000000
39.84620000000000000000
0.36360000000000000000
2296.90020000000000000000
61.83850000000000000000
None
19.92310000000000000000
None
19.92310000000000000000
59.76930000000000000000
None
59.76930000000000000000
21.91540000000000000000
16.68890000000000000000
183.23650000000000000000
None
None
21.91540000000000000000
None
10293.97330000000000000000
63.76170000000000000000
19.92310000000000000000
19.92310000000000000000
1.99230000000000000000
19.92310000000000000000
1.99230000000000000000
None
183.23650000000000000000
0.37640000000000000000
1.99230000000000000000
22.28680000000000000000
None
None
20.29450000000000000000
None
None
123.52340000000000000000
4.20920000000000000000
None
78.93260000000000000000
None
None
None
1.99230000000000000000
597.48540000000000000000
None
1.99230000000000000000
2.00000000000000000000
23.49540000000000000000
219.16680000000000000000
None
None
19.92310000000000000000
None
0.37070000000000000000
None
19.92310000000000000000
2.00000000000000000000
20.40290000000000000000
0.35400000000000000000
None
0.83980000000000000000
223.15440000000000000000
201.23130000000000000000
0.37070000000000000000
2.00000000000000000000
41.83850000000000000000
19.92310000000000000000
24.69730000000000000000
None
79.69240000000000000000
39.84630000000000000000
20.40290000000000000000
20.76290000000000000000
41.83850000000000000000
19.92310000000000000000
19.92310000000000000000
19.92310000000000000000
1.99230000000000000000
59.96060000000000000000
173.36890000000000000000
29.34420000000000000000
69936.81590000000000000000
22.28680000000000000000
None
696.41500000000000000000
None
19.92310000000000000000
19.92310000000000000000
0.36640000000000000000
47.83080000000000000000
19.92310000000000000000
None
158.71680000000000000000
None
63.76170000000000000000
5.97690000000000000000
38.02050000000000000000
16.68890000000000000000
39.84620000000000000000
19.92310000000000000000
None
57.94360000000000000000
39.84630000000000000000
2092.03830000000000000000
None
1.99230000000000000000
59.38940000000000000000
None
7.97690000000000000000
None
19.92310000000000000000
None
4.00000000000000000000
82.04840000000000000000
1.99230000000000000000
1.99230000000000000000
None
1.99230000000000000000
1.99230000000000000000
39.84620000000000000000
52.07700000000000000000
63.76170000000000000000
23.80100000000000000000
69936.81590000000000000000
19.92310000000000000000
None
None
63.76170000000000000000
None
1.99230000000000000000
19.92310000000000000000
19.92310000000000000000
39.84620000000000000000
53.73330000000000000000
10478.53420000000000000000
94.22310000000000000000
19.92310000000000000000
108.73650000000000000000
20.40290000000000000000
39.84630000000000000000
39.84620000000000000000
None
253.39660000000000000000
None
19.92310000000000000000
19.92310000000000000000
173.11760000000000000000
None
None
21.92310000000000000000
10227.59680000000000000000
0.09230000000000000000
168.77200000000000000000
2.00000000000000000000
None
0.83980000000000000000
39.26560000000000000000
None
39.84630000000000000000
1.99230000000000000000
None
34.77930000000000000000
1.99230000000000000000
None
1.99230000000000000000
273.31970000000000000000
None
None
None
19.92310000000000000000
39.84630000000000000000
83.67720000000000000000
173.36890000000000000000
72.00010000000000000000
39.84630000000000000000
None
2.00000000000000000000
None
39.84630000000000000000
0.83980000000000000000
296.79750000000000000000
83.67720000000000000000
None
4.77420000000000000000
54.70240000000000000000
None
486.76230000000000000000
90.34100000000000000000
0.09160000000000000000
2.00000000000000000000
19.92310000000000000000
303.20350000000000000000

303.20350000000000000000
305.20350000000000000000
19.92310000000000000000
146.93750000000000000000
283.28040000000000000000
38.44970000000000000000
83.67720000000000000000
303.20350000000000000000
283.68660000000000000000
None
425.91890000000000000000
321.73010000000000000000
40.21700000000000000000
123.52340000000000000000
25.92310000000000000000
55.54740000000000000000
822.77610000000000000000
2.00000000000000000000
19.92310000000000000000
1990.29820000000000000000
2.01240000000000000000
19.92310000000000000000
10478.53420000000000000000
2.00000000000000000000